"""Add attendance status to enrollment

Revision ID: 645afddcfaba
Revises: fd26853532ce
Create Date: 2026-06-13 18:01:59.446716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645afddcfaba'
down_revision = 'fd26853532ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance_status', sa.Enum('REGISTERED', 'ATTENDED', 'NO_SHOW', name='attendancestatus', native_enum=False), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_column('attendance_status')

    # ### end Alembic commands ###
