"""Create users table

Revision ID: 770f99f8b02c
Revises: 56a40f984bee
Create Date: 2026-06-13 12:32:12.061187

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '770f99f8b02c'
down_revision = '56a40f984bee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('ADMIN', 'COORDINATOR', 'PARTICIPANT'),
               type_=sa.Enum('ADMIN', 'COORDINATOR', 'PARTICIPANT', name='userrole', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('ADMIN', 'COORDINATOR', 'PARTICIPANT', name='userrole', native_enum=False),
               type_=mysql.ENUM('ADMIN', 'COORDINATOR', 'PARTICIPANT'),
               existing_nullable=False)

    # ### end Alembic commands ###
