"""Add unique feedback constraint

Revision ID: 805b4ecc5563
Revises: 645afddcfaba
Create Date: 2026-06-13 22:05:19.147465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '805b4ecc5563'
down_revision = '645afddcfaba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_feedback_per_enrollment_faculty', ['enrollment_id', 'faculty_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_constraint('unique_feedback_per_enrollment_faculty', type_='unique')

    # ### end Alembic commands ###
